"use strict";
// 100 Days Of Coding Challenge!
/** Question 90: Generating Random Numbers:
Write a function that generates a random number between 1 and 10, inclusive.*/
//----------------------------------------------------------------------------
/**
 * Generates a random number between 1 and 10, inclusive.
 * @returns A random number between 1 and 10.
 */
// Function "generateRandomNumber" to generate a random number between 1 and 10
function generateRandomNumber() {
    // Using Math.random() to generate a random number and scaling it to the desired range
    return Math.floor(Math.random() * 10) + 1;
}
// logging the random number generated by the function
const randomNum = generateRandomNumber();
console.log(randomNum); // Output: A random number between 1 and 10
